-- MySQL Script generated by MySQL Workbench
-- Wed 04 Mar 2015 04:50:34 PM EET
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Topic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Topic` (
  `idTopic` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `CREATEDIN` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `SUBJECT` VARCHAR(45) NULL,
  PRIMARY KEY (`idTopic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TOPICSDETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TOPICSDETAILS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TOPICSDETAILS` (
  `idTOPICSDETAILS` INT NOT NULL AUTO_INCREMENT,
  `COMMENT` VARCHAR(45) NULL,
  `CREATEDIN` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `TOPICID` INT NULL,
  PRIMARY KEY (`idTOPICSDETAILS`),
  INDEX `fk_table1_1_idx` (`TOPICID` ASC),
  CONSTRAINT `fk_table1_1`
    FOREIGN KEY (`TOPICID`)
    REFERENCES `mydb`.`Topic` (`idTopic`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
